name: stroke-outcome
channels:
  - defaults
  - conda-forge
dependencies:
  - jupyterlab
  - matplotlib
  - numpy
  - pip
  - pandas
  - python=3.10
  - scikit-learn
  - pip:
    - geopandas
    - contextily
    - mapclassify
    - stroke-outcome
    
